// Code generated by protoc-gen-go. DO NOT EDIT.
// source: adacore.proto

package adacorepb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// ResourceType - resource type
type ResourceType int32

const (
	// RT_PAGE - This is a page
	ResourceType_RT_PAGE ResourceType = 0
	// RT_OTHER - This is other resource
	ResourceType_RT_OTHER ResourceType = 1
)

var ResourceType_name = map[int32]string{
	0: "RT_PAGE",
	1: "RT_OTHER",
}
var ResourceType_value = map[string]int32{
	"RT_PAGE":  0,
	"RT_OTHER": 1,
}

func (x ResourceType) String() string {
	return proto.EnumName(ResourceType_name, int32(x))
}
func (ResourceType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_adacore_215e69c2bb12d46b, []int{0}
}

// MarkdownData - markdown data
type MarkdownData struct {
	// strData - markdown string data
	StrData string `protobuf:"bytes,1,opt,name=strData,proto3" json:"strData,omitempty"`
	// binaryData - binary data map, it's like images
	BinaryData map[string][]byte `protobuf:"bytes,2,rep,name=binaryData,proto3" json:"binaryData,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// templateName - template Name
	TemplateName string `protobuf:"bytes,10,opt,name=templateName,proto3" json:"templateName,omitempty"`
	// templateData - template data
	TemplateData         string   `protobuf:"bytes,11,opt,name=templateData,proto3" json:"templateData,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MarkdownData) Reset()         { *m = MarkdownData{} }
func (m *MarkdownData) String() string { return proto.CompactTextString(m) }
func (*MarkdownData) ProtoMessage()    {}
func (*MarkdownData) Descriptor() ([]byte, []int) {
	return fileDescriptor_adacore_215e69c2bb12d46b, []int{0}
}
func (m *MarkdownData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MarkdownData.Unmarshal(m, b)
}
func (m *MarkdownData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MarkdownData.Marshal(b, m, deterministic)
}
func (dst *MarkdownData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MarkdownData.Merge(dst, src)
}
func (m *MarkdownData) XXX_Size() int {
	return xxx_messageInfo_MarkdownData.Size(m)
}
func (m *MarkdownData) XXX_DiscardUnknown() {
	xxx_messageInfo_MarkdownData.DiscardUnknown(m)
}

var xxx_messageInfo_MarkdownData proto.InternalMessageInfo

func (m *MarkdownData) GetStrData() string {
	if m != nil {
		return m.StrData
	}
	return ""
}

func (m *MarkdownData) GetBinaryData() map[string][]byte {
	if m != nil {
		return m.BinaryData
	}
	return nil
}

func (m *MarkdownData) GetTemplateName() string {
	if m != nil {
		return m.TemplateName
	}
	return ""
}

func (m *MarkdownData) GetTemplateData() string {
	if m != nil {
		return m.TemplateData
	}
	return ""
}

// MarkdownStream - markdown stream data
type MarkdownStream struct {
	// totalLength - If the message is too long, it will send data in multiple msg, this is the total length.
	TotalLength int32 `protobuf:"varint,1,opt,name=totalLength,proto3" json:"totalLength,omitempty"`
	// curStart - The starting point of the current data (in bytes).
	CurStart int32 `protobuf:"varint,2,opt,name=curStart,proto3" json:"curStart,omitempty"`
	// curLength - The length of the current data (in bytes).
	CurLength int32 `protobuf:"varint,3,opt,name=curLength,proto3" json:"curLength,omitempty"`
	// hashData - This is the hash of each paragraph.
	HashData string `protobuf:"bytes,4,opt,name=hashData,proto3" json:"hashData,omitempty"`
	// totalHashData - If multiple messages return data, this is the hash value of all data, only sent in the last message.
	TotalHashData string `protobuf:"bytes,5,opt,name=totalHashData,proto3" json:"totalHashData,omitempty"`
	// data - binary data
	Data []byte `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`
	// error - error string
	Error string `protobuf:"bytes,100,opt,name=error,proto3" json:"error,omitempty"`
	// markdownData - If the data does not exceed 4mb, this is the data that is directly available.
	MarkdownData *MarkdownData `protobuf:"bytes,200,opt,name=markdownData,proto3" json:"markdownData,omitempty"`
	// token - API token
	Token                string   `protobuf:"bytes,300,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MarkdownStream) Reset()         { *m = MarkdownStream{} }
func (m *MarkdownStream) String() string { return proto.CompactTextString(m) }
func (*MarkdownStream) ProtoMessage()    {}
func (*MarkdownStream) Descriptor() ([]byte, []int) {
	return fileDescriptor_adacore_215e69c2bb12d46b, []int{1}
}
func (m *MarkdownStream) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MarkdownStream.Unmarshal(m, b)
}
func (m *MarkdownStream) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MarkdownStream.Marshal(b, m, deterministic)
}
func (dst *MarkdownStream) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MarkdownStream.Merge(dst, src)
}
func (m *MarkdownStream) XXX_Size() int {
	return xxx_messageInfo_MarkdownStream.Size(m)
}
func (m *MarkdownStream) XXX_DiscardUnknown() {
	xxx_messageInfo_MarkdownStream.DiscardUnknown(m)
}

var xxx_messageInfo_MarkdownStream proto.InternalMessageInfo

func (m *MarkdownStream) GetTotalLength() int32 {
	if m != nil {
		return m.TotalLength
	}
	return 0
}

func (m *MarkdownStream) GetCurStart() int32 {
	if m != nil {
		return m.CurStart
	}
	return 0
}

func (m *MarkdownStream) GetCurLength() int32 {
	if m != nil {
		return m.CurLength
	}
	return 0
}

func (m *MarkdownStream) GetHashData() string {
	if m != nil {
		return m.HashData
	}
	return ""
}

func (m *MarkdownStream) GetTotalHashData() string {
	if m != nil {
		return m.TotalHashData
	}
	return ""
}

func (m *MarkdownStream) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *MarkdownStream) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *MarkdownStream) GetMarkdownData() *MarkdownData {
	if m != nil {
		return m.MarkdownData
	}
	return nil
}

func (m *MarkdownStream) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

// ResourceInfo - resource infomation
type ResourceInfo struct {
	// hashName - hashname
	HashName string `protobuf:"bytes,1,opt,name=hashName,proto3" json:"hashName,omitempty"`
	// citedTimes - cited times
	CitedTimes int32 `protobuf:"varint,2,opt,name=citedTimes,proto3" json:"citedTimes,omitempty"`
	// createTime - Creation time in seconds
	CreateTime int64 `protobuf:"varint,3,opt,name=createTime,proto3" json:"createTime,omitempty"`
	// type - resource type
	Type ResourceType `protobuf:"varint,4,opt,name=type,proto3,enum=adacorepb.ResourceType" json:"type,omitempty"`
	// children - children resource hashname
	Children             []string `protobuf:"bytes,10,rep,name=children,proto3" json:"children,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResourceInfo) Reset()         { *m = ResourceInfo{} }
func (m *ResourceInfo) String() string { return proto.CompactTextString(m) }
func (*ResourceInfo) ProtoMessage()    {}
func (*ResourceInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_adacore_215e69c2bb12d46b, []int{2}
}
func (m *ResourceInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResourceInfo.Unmarshal(m, b)
}
func (m *ResourceInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResourceInfo.Marshal(b, m, deterministic)
}
func (dst *ResourceInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResourceInfo.Merge(dst, src)
}
func (m *ResourceInfo) XXX_Size() int {
	return xxx_messageInfo_ResourceInfo.Size(m)
}
func (m *ResourceInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ResourceInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ResourceInfo proto.InternalMessageInfo

func (m *ResourceInfo) GetHashName() string {
	if m != nil {
		return m.HashName
	}
	return ""
}

func (m *ResourceInfo) GetCitedTimes() int32 {
	if m != nil {
		return m.CitedTimes
	}
	return 0
}

func (m *ResourceInfo) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *ResourceInfo) GetType() ResourceType {
	if m != nil {
		return m.Type
	}
	return ResourceType_RT_PAGE
}

func (m *ResourceInfo) GetChildren() []string {
	if m != nil {
		return m.Children
	}
	return nil
}

// ReplyMarkdown - reply
type ReplyMarkdown struct {
	// url - url
	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	// hashName - hashname
	HashName string `protobuf:"bytes,2,opt,name=hashName,proto3" json:"hashName,omitempty"`
	// lstRes - resource list
	LstRes               []*ResourceInfo `protobuf:"bytes,10,rep,name=lstRes,proto3" json:"lstRes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ReplyMarkdown) Reset()         { *m = ReplyMarkdown{} }
func (m *ReplyMarkdown) String() string { return proto.CompactTextString(m) }
func (*ReplyMarkdown) ProtoMessage()    {}
func (*ReplyMarkdown) Descriptor() ([]byte, []int) {
	return fileDescriptor_adacore_215e69c2bb12d46b, []int{3}
}
func (m *ReplyMarkdown) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyMarkdown.Unmarshal(m, b)
}
func (m *ReplyMarkdown) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyMarkdown.Marshal(b, m, deterministic)
}
func (dst *ReplyMarkdown) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyMarkdown.Merge(dst, src)
}
func (m *ReplyMarkdown) XXX_Size() int {
	return xxx_messageInfo_ReplyMarkdown.Size(m)
}
func (m *ReplyMarkdown) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyMarkdown.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyMarkdown proto.InternalMessageInfo

func (m *ReplyMarkdown) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *ReplyMarkdown) GetHashName() string {
	if m != nil {
		return m.HashName
	}
	return ""
}

func (m *ReplyMarkdown) GetLstRes() []*ResourceInfo {
	if m != nil {
		return m.LstRes
	}
	return nil
}

func init() {
	proto.RegisterType((*MarkdownData)(nil), "adacorepb.MarkdownData")
	proto.RegisterMapType((map[string][]byte)(nil), "adacorepb.MarkdownData.BinaryDataEntry")
	proto.RegisterType((*MarkdownStream)(nil), "adacorepb.MarkdownStream")
	proto.RegisterType((*ResourceInfo)(nil), "adacorepb.ResourceInfo")
	proto.RegisterType((*ReplyMarkdown)(nil), "adacorepb.ReplyMarkdown")
	proto.RegisterEnum("adacorepb.ResourceType", ResourceType_name, ResourceType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AdaCoreServiceClient is the client API for AdaCoreService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AdaCoreServiceClient interface {
	// buildWithMarkdown - build with markdown
	BuildWithMarkdown(ctx context.Context, opts ...grpc.CallOption) (AdaCoreService_BuildWithMarkdownClient, error)
}

type adaCoreServiceClient struct {
	cc *grpc.ClientConn
}

func NewAdaCoreServiceClient(cc *grpc.ClientConn) AdaCoreServiceClient {
	return &adaCoreServiceClient{cc}
}

func (c *adaCoreServiceClient) BuildWithMarkdown(ctx context.Context, opts ...grpc.CallOption) (AdaCoreService_BuildWithMarkdownClient, error) {
	stream, err := c.cc.NewStream(ctx, &_AdaCoreService_serviceDesc.Streams[0], "/adacorepb.AdaCoreService/buildWithMarkdown", opts...)
	if err != nil {
		return nil, err
	}
	x := &adaCoreServiceBuildWithMarkdownClient{stream}
	return x, nil
}

type AdaCoreService_BuildWithMarkdownClient interface {
	Send(*MarkdownStream) error
	CloseAndRecv() (*ReplyMarkdown, error)
	grpc.ClientStream
}

type adaCoreServiceBuildWithMarkdownClient struct {
	grpc.ClientStream
}

func (x *adaCoreServiceBuildWithMarkdownClient) Send(m *MarkdownStream) error {
	return x.ClientStream.SendMsg(m)
}

func (x *adaCoreServiceBuildWithMarkdownClient) CloseAndRecv() (*ReplyMarkdown, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(ReplyMarkdown)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// AdaCoreServiceServer is the server API for AdaCoreService service.
type AdaCoreServiceServer interface {
	// buildWithMarkdown - build with markdown
	BuildWithMarkdown(AdaCoreService_BuildWithMarkdownServer) error
}

func RegisterAdaCoreServiceServer(s *grpc.Server, srv AdaCoreServiceServer) {
	s.RegisterService(&_AdaCoreService_serviceDesc, srv)
}

func _AdaCoreService_BuildWithMarkdown_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AdaCoreServiceServer).BuildWithMarkdown(&adaCoreServiceBuildWithMarkdownServer{stream})
}

type AdaCoreService_BuildWithMarkdownServer interface {
	SendAndClose(*ReplyMarkdown) error
	Recv() (*MarkdownStream, error)
	grpc.ServerStream
}

type adaCoreServiceBuildWithMarkdownServer struct {
	grpc.ServerStream
}

func (x *adaCoreServiceBuildWithMarkdownServer) SendAndClose(m *ReplyMarkdown) error {
	return x.ServerStream.SendMsg(m)
}

func (x *adaCoreServiceBuildWithMarkdownServer) Recv() (*MarkdownStream, error) {
	m := new(MarkdownStream)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _AdaCoreService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "adacorepb.AdaCoreService",
	HandlerType: (*AdaCoreServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "buildWithMarkdown",
			Handler:       _AdaCoreService_BuildWithMarkdown_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "adacore.proto",
}

func init() { proto.RegisterFile("adacore.proto", fileDescriptor_adacore_215e69c2bb12d46b) }

var fileDescriptor_adacore_215e69c2bb12d46b = []byte{
	// 529 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x53, 0x5f, 0x8b, 0xd3, 0x5e,
	0x10, 0xdd, 0xa4, 0x7f, 0x76, 0x3b, 0x49, 0xfb, 0xeb, 0xef, 0xa2, 0x18, 0x8b, 0x48, 0x09, 0x82,
	0x55, 0xa1, 0x42, 0x7d, 0x11, 0xd1, 0x87, 0x55, 0xcb, 0xae, 0xb0, 0xfe, 0xe1, 0xb6, 0xe0, 0x9b,
	0xcb, 0x6d, 0x32, 0xda, 0xd0, 0x34, 0x37, 0xdc, 0xdc, 0xac, 0xe4, 0x3b, 0xe9, 0x93, 0x5f, 0xc2,
	0x8f, 0xe4, 0xa3, 0xdc, 0x69, 0x93, 0x26, 0xcb, 0xfa, 0x96, 0x33, 0x73, 0x66, 0xe6, 0x9c, 0x99,
	0x1b, 0xe8, 0x8b, 0x50, 0x04, 0x52, 0xe1, 0x34, 0x55, 0x52, 0x4b, 0xd6, 0xdb, 0xc3, 0x74, 0xe5,
	0xff, 0xb1, 0xc0, 0x7d, 0x2f, 0xd4, 0x26, 0x94, 0xdf, 0x93, 0xb7, 0x42, 0x0b, 0xe6, 0xc1, 0x71,
	0xa6, 0x95, 0xf9, 0xf4, 0xac, 0xb1, 0x35, 0xe9, 0xf1, 0x12, 0xb2, 0x33, 0x80, 0x55, 0x94, 0x08,
	0x55, 0x50, 0xd2, 0x1e, 0xb7, 0x26, 0xce, 0xec, 0xe1, 0xb4, 0x6a, 0x35, 0xad, 0xb7, 0x99, 0xbe,
	0xae, 0x98, 0xf3, 0x44, 0xab, 0x82, 0xd7, 0x4a, 0x99, 0x0f, 0xae, 0xc6, 0x6d, 0x1a, 0x0b, 0x8d,
	0x1f, 0xc4, 0x16, 0x3d, 0xa0, 0x39, 0x8d, 0x58, 0x9d, 0x43, 0xe3, 0x9c, 0x26, 0xc7, 0xc4, 0x46,
	0xaf, 0xe0, 0xbf, 0x6b, 0x63, 0xd8, 0x10, 0x5a, 0x1b, 0x2c, 0xf6, 0xca, 0xcd, 0x27, 0xbb, 0x05,
	0x9d, 0x2b, 0x11, 0xe7, 0xe8, 0xd9, 0x63, 0x6b, 0xe2, 0xf2, 0x1d, 0x78, 0x61, 0x3f, 0xb7, 0xfc,
	0x9f, 0x36, 0x0c, 0x4a, 0xcd, 0x0b, 0xad, 0x50, 0x6c, 0xd9, 0x18, 0x1c, 0x2d, 0xb5, 0x88, 0x2f,
	0x30, 0xf9, 0xa6, 0xd7, 0xd4, 0xa6, 0xc3, 0xeb, 0x21, 0x36, 0x82, 0x93, 0x20, 0x57, 0x0b, 0x2d,
	0x94, 0xa6, 0x8e, 0x1d, 0x5e, 0x61, 0x76, 0x0f, 0x7a, 0x41, 0xae, 0xf6, 0xb5, 0x2d, 0x4a, 0x1e,
	0x02, 0xa6, 0x72, 0x2d, 0xb2, 0x35, 0xb9, 0x69, 0x93, 0xbe, 0x0a, 0xb3, 0x07, 0xd0, 0xa7, 0x21,
	0xe7, 0x25, 0xa1, 0x43, 0x84, 0x66, 0x90, 0x31, 0x68, 0x87, 0x26, 0xd9, 0x25, 0x27, 0xf4, 0x6d,
	0xec, 0xa1, 0x52, 0x52, 0x79, 0x21, 0x55, 0xec, 0x00, 0x7b, 0x09, 0xee, 0xb6, 0x76, 0x0d, 0xef,
	0xb7, 0x71, 0xe2, 0xcc, 0xee, 0xfc, 0xe3, 0x5a, 0xbc, 0xc1, 0x66, 0xb7, 0xa1, 0xa3, 0xe5, 0x06,
	0x13, 0xef, 0x87, 0xbd, 0x6b, 0x4a, 0xc8, 0xff, 0x65, 0x81, 0xcb, 0x31, 0x93, 0xb9, 0x0a, 0xf0,
	0x5d, 0xf2, 0x55, 0x96, 0x8e, 0xe8, 0x86, 0xd6, 0xc1, 0x11, 0xdd, 0xef, 0x3e, 0x40, 0x10, 0x69,
	0x0c, 0x97, 0xd1, 0x16, 0xb3, 0xfd, 0xa6, 0x6a, 0x11, 0xca, 0x2b, 0x14, 0x1a, 0x0d, 0xa4, 0x65,
	0xb5, 0x78, 0x2d, 0xc2, 0x9e, 0x40, 0x5b, 0x17, 0x29, 0xd2, 0xa6, 0x06, 0x0d, 0xe1, 0xa5, 0x84,
	0x65, 0x91, 0x22, 0x27, 0x12, 0x1d, 0x65, 0x1d, 0xc5, 0xa1, 0xc2, 0xc4, 0x83, 0x71, 0xcb, 0x08,
	0x29, 0xb1, 0x9f, 0x40, 0x9f, 0x63, 0x1a, 0x17, 0xa5, 0x5f, 0xf3, 0x44, 0x72, 0x15, 0x97, 0x4f,
	0x24, 0x57, 0x71, 0xc3, 0x87, 0x7d, 0xcd, 0xc7, 0x53, 0xe8, 0xc6, 0x99, 0xe6, 0x98, 0x51, 0x63,
	0xe7, 0x46, 0x25, 0x66, 0x19, 0x7c, 0x4f, 0x7b, 0xfc, 0xe8, 0xb0, 0x24, 0xa3, 0x90, 0x39, 0x70,
	0xcc, 0x97, 0x97, 0x9f, 0x4e, 0xcf, 0xe6, 0xc3, 0x23, 0xe6, 0xc2, 0x09, 0x5f, 0x5e, 0x7e, 0x5c,
	0x9e, 0xcf, 0xf9, 0xd0, 0x9a, 0x7d, 0x81, 0xc1, 0x69, 0x28, 0xde, 0x48, 0x85, 0x0b, 0x54, 0x57,
	0x51, 0x80, 0xec, 0x02, 0xfe, 0x5f, 0xe5, 0x51, 0x1c, 0x7e, 0x8e, 0xf4, 0xba, 0x12, 0x7c, 0xf7,
	0x86, 0xab, 0xed, 0xde, 0xeb, 0xc8, 0x6b, 0xa8, 0xa9, 0xb9, 0xf4, 0x8f, 0x26, 0xd6, 0xaa, 0x4b,
	0x7f, 0xfb, 0xb3, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x77, 0x94, 0x4b, 0x05, 0xfe, 0x03, 0x00,
	0x00,
}
