// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chatbot.proto

package adacorepb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// ChatBotData - chatbot data
type ChatBotData struct {
	DataNums             int64    `protobuf:"varint,1,opt,name=dataNums,proto3" json:"dataNums,omitempty"`
	PageNums             int64    `protobuf:"varint,2,opt,name=pageNums,proto3" json:"pageNums,omitempty"`
	BuildNums            int64    `protobuf:"varint,3,opt,name=buildNums,proto3" json:"buildNums,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChatBotData) Reset()         { *m = ChatBotData{} }
func (m *ChatBotData) String() string { return proto.CompactTextString(m) }
func (*ChatBotData) ProtoMessage()    {}
func (*ChatBotData) Descriptor() ([]byte, []int) {
	return fileDescriptor_chatbot_05e8024fa78e5e20, []int{0}
}
func (m *ChatBotData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatBotData.Unmarshal(m, b)
}
func (m *ChatBotData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatBotData.Marshal(b, m, deterministic)
}
func (dst *ChatBotData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatBotData.Merge(dst, src)
}
func (m *ChatBotData) XXX_Size() int {
	return xxx_messageInfo_ChatBotData.Size(m)
}
func (m *ChatBotData) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatBotData.DiscardUnknown(m)
}

var xxx_messageInfo_ChatBotData proto.InternalMessageInfo

func (m *ChatBotData) GetDataNums() int64 {
	if m != nil {
		return m.DataNums
	}
	return 0
}

func (m *ChatBotData) GetPageNums() int64 {
	if m != nil {
		return m.PageNums
	}
	return 0
}

func (m *ChatBotData) GetBuildNums() int64 {
	if m != nil {
		return m.BuildNums
	}
	return 0
}

// UserData - user data
type UserData struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	DataNums             int64    `protobuf:"varint,2,opt,name=dataNums,proto3" json:"dataNums,omitempty"`
	PageNums             int64    `protobuf:"varint,3,opt,name=pageNums,proto3" json:"pageNums,omitempty"`
	BuildNums            int64    `protobuf:"varint,4,opt,name=buildNums,proto3" json:"buildNums,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserData) Reset()         { *m = UserData{} }
func (m *UserData) String() string { return proto.CompactTextString(m) }
func (*UserData) ProtoMessage()    {}
func (*UserData) Descriptor() ([]byte, []int) {
	return fileDescriptor_chatbot_05e8024fa78e5e20, []int{1}
}
func (m *UserData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserData.Unmarshal(m, b)
}
func (m *UserData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserData.Marshal(b, m, deterministic)
}
func (dst *UserData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserData.Merge(dst, src)
}
func (m *UserData) XXX_Size() int {
	return xxx_messageInfo_UserData.Size(m)
}
func (m *UserData) XXX_DiscardUnknown() {
	xxx_messageInfo_UserData.DiscardUnknown(m)
}

var xxx_messageInfo_UserData proto.InternalMessageInfo

func (m *UserData) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *UserData) GetDataNums() int64 {
	if m != nil {
		return m.DataNums
	}
	return 0
}

func (m *UserData) GetPageNums() int64 {
	if m != nil {
		return m.PageNums
	}
	return 0
}

func (m *UserData) GetBuildNums() int64 {
	if m != nil {
		return m.BuildNums
	}
	return 0
}

func init() {
	proto.RegisterType((*ChatBotData)(nil), "adacorepb.ChatBotData")
	proto.RegisterType((*UserData)(nil), "adacorepb.UserData")
}

func init() { proto.RegisterFile("chatbot.proto", fileDescriptor_chatbot_05e8024fa78e5e20) }

var fileDescriptor_chatbot_05e8024fa78e5e20 = []byte{
	// 155 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0xce, 0x48, 0x2c,
	0x49, 0xca, 0x2f, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x4c, 0x4c, 0x49, 0x4c, 0xce,
	0x2f, 0x4a, 0x2d, 0x48, 0x52, 0x4a, 0xe6, 0xe2, 0x76, 0xce, 0x48, 0x2c, 0x71, 0xca, 0x2f, 0x71,
	0x49, 0x2c, 0x49, 0x14, 0x92, 0xe2, 0xe2, 0x48, 0x49, 0x2c, 0x49, 0xf4, 0x2b, 0xcd, 0x2d, 0x96,
	0x60, 0x54, 0x60, 0xd4, 0x60, 0x0e, 0x82, 0xf3, 0x41, 0x72, 0x05, 0x89, 0xe9, 0xa9, 0x60, 0x39,
	0x26, 0x88, 0x1c, 0x8c, 0x2f, 0x24, 0xc3, 0xc5, 0x99, 0x54, 0x9a, 0x99, 0x93, 0x02, 0x96, 0x64,
	0x06, 0x4b, 0x22, 0x04, 0x94, 0xca, 0xb8, 0x38, 0x42, 0x8b, 0x53, 0x8b, 0xc0, 0x36, 0x88, 0x70,
	0xb1, 0x96, 0xe4, 0x67, 0xa7, 0xe6, 0x81, 0x8d, 0xe7, 0x0c, 0x82, 0x70, 0x50, 0xec, 0x65, 0xc2,
	0x63, 0x2f, 0x33, 0x3e, 0x7b, 0x59, 0xd0, 0xec, 0x4d, 0x62, 0x03, 0x7b, 0xd7, 0x18, 0x10, 0x00,
	0x00, 0xff, 0xff, 0x99, 0x7f, 0xc3, 0xad, 0xff, 0x00, 0x00, 0x00,
}
